### ISSUE TITLE
[11.0] Problem installing some modules

### ISSUE THREAD

**Issue by SalahAdDin** [guohuadeng/app-odoo#14]
I cloned this repository and I added its path to the options and I run odoo with all add-ons.
But, I get this bug:
![roto](https://user-images.githubusercontent.com/5034215/41716863-7cb04f8c-7560-11e8-8d7a-66c28184613f.png)

I don't get this problem with `app_odoo_customize`(i deleted all other modules and I tested it).

**UPDATE:**
The problem exists with `app_product_type_sequence` and `app_stock_picking_type_group`.

Thank you!

**Comment by guohuadeng** [comment]
we move "app_product_type_sequence"  to  http://www.odoo.com/apps/modules/12.0/app_product_auto_code/

and "app_stock_picking_type_group" we found no error
