### ISSUE TITLE
odoo 13翻译错误

### ISSUE THREAD

**Issue by linzhihao0826** [guohuadeng/app-odoo#33]
老哥，你害我找的好苦啊，一点进去询价单的打印，就抛bug出来。你在Transifex里面的翻译，前面少了个 <'> ，后面的<object.name> 解析式不应该翻译的 : (

**Comment by guohuadeng** [comment]
具体哪里？

**Comment by linzhihao0826** [comment]
嗯，在采购里面的一个翻译
'请求引用........<对象.名称>

**Comment by guohuadeng** [comment]
tks
