### ISSUE TITLE
[14.0]app_odoo_customizs 在app tree视图界面不支持批量卸载

### ISSUE THREAD

**Issue by lonelyleaves** [guohuadeng/app-odoo#38]
如题，在应用的列表界面，勾选多个已安装的模块，下拉更多选择卸载功能，只能卸载第一个模块，其他的模块不能卸载
log有类似报错：odoo.models: Comparing apples and oranges: ir.module.module(155,)debug未找到失败的原因

**Comment by guohuadeng** [comment]
要选中相关依赖模块一起才行
