### ISSUE TITLE
你要安装的模块'app_base_chinese'依赖于‘app_base’,请问app_base在哪有下载

### ISSUE THREAD

**Issue by eysp** [guohuadeng/app-odoo#45]
你要安装的模块'app_base_chinese'依赖于‘app_base’,请问app_base在哪有下载

**Comment by guohuadeng** [comment]
Odoo市场搜索 app_base

发件人: eysp ***@***.***
发送时间: 2021年7月20日, 星期二 15:19
收件人: guohuadeng/app-odoo ***@***.***>
抄送: Subscribed ***@***.***>
主题: [guohuadeng/app-odoo] 你要安装的模块'app_base_chinese'依赖于‘app_base’,请问app_base在哪有下载 (#45)


你要安装的模块'app_base_chinese'依赖于‘app_base’,请问app_base在哪有下载
