### ISSUE TITLE
The uninstallation and reinstallation failed (l10n_cn_standard_latest14)卸载重装出错

### ISSUE THREAD

**Issue by erpstudy** [guohuadeng/app-odoo#49]
l10n_cn_standard_latest 14 ,卸载原先的版本 14.21.11.07，安装新的版本14.21.11.09，安装不上，提示出错

odoo\http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing file: extra-addons/l10n_cn_standard_latest/data/account_chart_template_data.xml:14, near
<function model="account.chart.template" name="try_loading">
            <value eval="[ref('l10n_cn_standard_latest.l10n_chart_china_standard_business_latest')]"/>
        </function>

**Comment by guohuadeng** [comment]
must us app_odoo_customize to clear chart first,  then upgrade
