### ISSUE TITLE
app_chatgpt - chat_count

### ISSUE THREAD

**Issue by steven-bouillon** [guohuadeng/app-odoo#55]
Below traceback on chat_count

> Traceback (most recent call last):
>   File "/opt/odoo/odoo/http.py", line 1584, in _serve_db
>     return service_model.retrying(self._serve_ir_http, self.env)
>   File "/opt/odoo/odoo/service/model.py", line 134, in retrying
>     result = func()
>   File "/opt/odoo/odoo/http.py", line 1611, in _serve_ir_http
>     response = self.dispatcher.dispatch(rule.endpoint, args)
>   File "/opt/odoo/odoo/http.py", line 1808, in dispatch
>     result = self.request.registry['ir.http']._dispatch(endpoint)
>   File "/opt/odoo/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
>     response = super()._dispatch(endpoint)
>   File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
>     result = endpoint(**request.params)
>   File "/opt/odoo/odoo/http.py", line 699, in route_wrapper
>     result = endpoint(self, *args, **params_ok)
>   File "/opt/odoo/odoo/addons/mail/controllers/discuss.py", line 236, in mail_message_post
>     return thread.message_post(**{key: value for key, value in post_data.items() if key in self._get_allowed_message_post_params()}).message_format()[0]
>   File "/opt/odoo/odoo/addons/mail/models/mail_channel.py", line 603, in message_post
>     return super(Channel, self.with_context(mail_create_nosubscribe=True, mail_post_autofollow=False)).message_post(message_type=message_type, **kwargs)
>   File "/opt/odoo/odoo/addons/rating/models/mail_thread.py", line 15, in message_post
>     message = super(MailThread, self).message_post(**kwargs)
>   File "/opt/odoo/odoo/addons/mail/models/mail_thread.py", line 2024, in message_post
>     self._notify_thread(new_message, msg_values, **notif_kwargs)
>   File "/mnt/extra-addons/app-odoo/app_chatgpt/models/mail_channel.py", line 180, in _notify_thread
>     chat_count = self.chat_count
>
> AttributeError: 'mail.channel' object has no attribute 'chat_count'

**Comment by guohuadeng** [comment]
fixed in odoo 16
