### ISSUE TITLE
14.0 - Only types many2one, selection are supported for category (found type many2many)

### ISSUE THREAD

**Issue by whotopia** [guohuadeng/app-odoo#57]
On several of the superbar addons e.g. app_mail_superbar, when I add them, I get the error

`Only types many2one, selection are supported for category (found type many2many)`

upon going to the parts of the UI that use the addon.   

Also happening for me with app_product_superbar_pro

**Comment by guohuadeng** [comment]
you need to search and buy 'app_web_superbar'
