### ISSUE TITLE
Internal server error with new users

### ISSUE THREAD

**Issue by rogerv95** [guohuadeng/app-odoo#8]
I'm not sure if that is an issue or I'm missing something. I had a fresh odoo install and when I got everything configured and running with all addons installed and wanted to invite new users when the user set the new passsword and tryied to log in for the first time the server gives back a internal server error.
If I log in back again (after clearing cache) to the administrator account it works as normal but whenever I try to log in with new users it won't work. 
If I uninstall&remove the app-odoo from the addons folder I can access odoo with the new users without problems.

I will provide any information you think would be useful.

**Comment by UnixedIT** [comment]
I have the same issue.

**Comment by rogerv95** [comment]
I believe it's a permissions issue. I've found that if I give administrator rights to any user it will be able to log-in without a problem. If the user doesn't have administrator rights then you get the internal server error as a result of not having access rights. Maybe this could be solved so the language switching menu could work for any type of user without administrator access.

**Comment by guohuadeng** [comment]
please download the last version
